version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: abin0x/new-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=university.settings
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: abin0x/new-frontend:latest
    ports:
      - "3001:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres.hfhnwfsorfqbhipnlfwx
      POSTGRES_PASSWORD: pOZLCLQKaSEzUHtH
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
